# Generated by Django 4.1.4 on 2023-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab_file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnabfile",
            name="file",
            field=models.FileField(upload_to="uploads"),
        ),
    ]
