# Generated by Django 4.1.4 on 2023-01-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab_file", "0003_remove_cnabfile_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnabdata",
            name="date",
            field=models.CharField(max_length=8),
        ),
    ]
