# Generated by Django 4.1.4 on 2023-01-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab_file", "0005_alter_cnabdata_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnabdata",
            name="card",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="cnabdata",
            name="date",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="cnabdata",
            name="owner",
            field=models.CharField(max_length=127),
        ),
    ]
